Update bashvm-create-vm.sh
Having the topology tag in manually created vm's will cause the current vcpu's to not be changeable with virsh as the error below.

error: invalid argument: CPU topology doesn't match the desired vcpu count

Removing the topology tags fix's this issue.